[workspace]

members = ["egonlang-cli", "egonlang-core", "egonlang-diagnostics", "egonlang-errors", "egonlang-lsp", "egonlang-types", "egonlang-verifier", "span", "str-idxpos", "tracelog"]

resolver = "2"
