[package]
name = "egonlang-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egonlang-core = { path = "../egonlang-core" }

[[bin]]
name = "egon"
path = "src/main.rs"