default:
  @just --list

build: clean
    source ~/.nvm/nvm.sh
    npm ci
    npm run build
    npm run package

clean:
    rm -rf out/* node_modules/

fmt:
    echo "No formatter in place"

lint:
    echo "No linter in place"
